version: '3'
services:
    mongo:
        image: mongo
        container_name: mongo
        ports:
            - "27017:27017"
        
    flask:
        build: ./server
        image: tiangolo/uwsgi-nginx-flask:python3.8
        ports:
            - "80:80"
        volumes:
            - ./server:/usr/src/app
        environment:
            - FLASK_ENV=development
    client:
        build: ./client/vite
        image: vue3:latest
        volumes:
        - ./client:/app
        ports:
            - "5000:5000"
